exports.errors = {
  invalidCredentials: {code: '403', reason: 'invalid credentials.'},
  emptyCredentials: {code: '403', reason: 'empty credentials.'},
  emptyClientRole: {code: '400', reason: 'client role cannot be empty.'},
  emptyClientAddresses: {code: '400', reason: 'client address cannot be empty.'},
  emptyClientEmails: {code: '400', reason: 'client email cannot be empty.'},
  emptyReqBody: {code: '400', reason: 'request body is empty or not present'},
  invalidClientUuid: {code: '400', reason: 'client with given UUID was not found.'},
  errAddingClient: {code: '500', reason: 'error adding client to DB.'},
  userWithGivenUsernameNotFound: {code: '400', reason: 'user with given username not found.'},
  roleWithGivenUuidNotFound: {code: '400', reason: 'role with given uuid not found.'},
  rolewithGivenNameNotFound: {code: '400', reason: 'role with given name not found.'},
  rolewithGivenNameAlreadyExists: {code: '400', reason: 'role with given name already exists.'},
  clientNotFound: {code: '400', reason: 'client with given uuid not found.'},
};
