exports.errors = {
  invalidCredentials: {code: '403', reason: 'invalid credentials.'},
  emptyCredentials: {code: '403', reason: 'empty credentials.'},
  emptyClientRole: {code: '400', reason: 'client role cannot be empty.'},
  emptyClientAddresses: {code: '400', reason: 'client address cannot be empty.'},
  emptyClientEmails: {code: '400', reason: 'client email cannot be empty.'},
  emptyReqBody: {code: '400', reason: 'request body is empty or not present'},
  invalidClientUuid: {code: '400', reason: 'client with given UUID was not found.'},
  userWithGivenUsernameNotFound: {code: '400', reason: 'user with given username not found.'},
  roleWithGivenUuidNotFound: {code: '400', reason: 'role with given uuid not found.'},
  rolewithGivenNameNotFound: {code: '400', reason: 'role with given name not found.'},
  rolewithGivenNameAlreadyExists: {code: '400', reason: 'role with given name already exists.'},
  clientNotFound: {code: '400', reason: 'client with given uuid not found.'},
  emptyOrUnknownEvent: {code: '400', reason: 'empty or unknown event was received.'},
  emptyOrUnknownInstance: {code: '400', reason: 'Cannot create new instance. Empty or unknown data was received in request body.'},
  emptyFirstNameInInstance: {code: '400', reason: 'Cannot create new instance. First name cannot be empty.'},
  emptyLastNameInInstance: {code: '400', reason: 'Cannot create new instance. Last name cannot be empty.'},
  emptyEmailInInstance: {code: '400', reason: 'Cannot create new instance. Email cannot be empty.'},
  emptyOrganizationInInstance: {code: '400', reason: 'Cannot create new instance. Organization cannot be empty.'},
  errAddingClient: {code: '500', reason: 'error adding client to DB.'},
  couldNotInitializeDb: {code: '500', reason: 'could not initialize DB.'},
  couldNotInitializeInstance: {code: '500', reason: 'error creating new instance.'},
  couldNotCreateClientToInitializeInstance: {code: '500', reason: 'Cannot create new instance. Creating client data failed.'},
};
